# Generated by Django 3.2.6 on 2022-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkituser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkitspaceprovider',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parkitspaceprovider',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
